name: tests

on: [push, pull_request]

jobs:
  cxx-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get -qq -y install g++

    #   - name: Build
    #     run: |
    #       make wordle

      - name: Compile
        run: |
            g++ -o test_wordle test_wordle.cpp

      - name: Test
        run: |
            ./test_wordle